export default [
  {
    homeTeam: 'Boston Bruins',
    awayTeam: 'Washington Capitals',
    homeScore: 2,
    awayScore: 2,
    period: 3,
    periodOrdinal: '3rd',
    timeRemaining: '1:21',
    startTime: '2022-10-12T23:00:00Z',
    started: true,
    finished: false,
  },
  {
    homeTeam: 'Columbus Blue Jackets',
    awayTeam: 'Carolina Hurricanes',
    homeScore: 1,
    awayScore: 0,
    period: 3,
    periodOrdinal: '3rd',
    timeRemaining: '4:20',
    startTime: '2022-10-12T23:00:00Z',
    started: true,
    finished: false,
  },
  {
    homeTeam: 'Toronto Maple Leafs',
    awayTeam: 'Montréal Canadiens',
    homeScore: 3,
    awayScore: 1,
    period: 3,
    periodOrdinal: 'Final',
    timeRemaining: '0:00',
    startTime: '2022-10-12T23:00:00Z',
    started: true,
    finished: true,
  },
  {
    homeTeam: 'Chicago Blackhawks',
    awayTeam: 'Colorado Avalanche',
    homeScore: 0,
    awayScore: 0,
    period: 1,
    periodOrdinal: '1st',
    timeRemaining: '19:41',
    startTime: '2022-10-13T01:30:00Z',
    started: true,
    finished: false,
  },
  {
    homeTeam: 'Seattle Kraken',
    awayTeam: 'Anaheim Ducks',
    homeScore: 0,
    awayScore: 0,
    period: 0,
    periodOrdinal: null,
    timeRemaining: '20:00',
    startTime: '2022-10-13T02:00:00Z',
    started: false,
    finished: false,
  },
  {
    homeTeam: 'Vancouver Canucks',
    awayTeam: 'Edmonton Oilers',
    homeScore: 0,
    awayScore: 0,
    period: 0,
    periodOrdinal: null,
    timeRemaining: '20:00',
    startTime: '2022-10-13T02:00:00Z',
    started: false,
    finished: false,
  },
];
