const path = (team) => require(`../assets/logos/${team}.svg`);

export default {
  'Anaheim Ducks': path('ANA'),
  'Arizona Coyotes': path('PHX'),
  'Boston Bruins': path('BOS'),
  'Buffalo Sabres': path('BUF'),
  'Carolina Hurricanes': path('CAR'),
  'Columbus Blue Jackets': path('CBJ'),
  'Calgary Flames': path('CGY'),
  'Chicago Blackhawks': path('CHI'),
  'Colorado Avalanche': path('COL'),
  'Dallas Stars': path('DAL'),
  'Detroit Red Wings': path('DET'),
  'Edmonton Oilers': path('EDM'),
  'Florida Panthers': path('FLA'),
  'Los Angeles Kings': path('LAK'),
  'Minnesota Wild': path('MIN'),
  'Montreal Canadiens': path('MTL'),
  'Montréal Canadiens': path('MTL'),
  'New Jersey Devils': path('NJD'),
  'Nashville Predators': path('NSH'),
  'New York Islanders': path('NYI'),
  'New York Rangers': path('NYR'),
  'Ottawa Senators': path('OTT'),
  'Philadelphia Flyers': path('PHI'),
  'Pheonix Coyotes': path('PHX'),
  'Pittsburgh Penguins': path('PIT'),
  'Seattle Kraken': path('SEA'),
  'San Jose Sharks': path('SJS'),
  'St Louis Blues': path('STL'),
  'St. Louis Blues': path('STL'),
  'Tampa Bay Lightning': path('TBL'),
  'Toronto Maple Leafs': path('TOR'),
  'Vancouver Canucks': path('VAN'),
  'Vegas Golden Knights': path('VGK'),
  'Winnipeg Jets': path('WPG'),
  'Washington Capitals': path('WSH'),
};
